[package]
name = "embedded-builder"
version = "0.1.1"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
license = "MIT"
description = "Helper objects and macros for building embedded hardware interfaces"

[dependencies]
